"""List all extra dependencies to be installed for Konfuzio SDK's AIs and dev mode."""

EXTRAS = {
    'dev': [
        'autodoc_pydantic==2.2.0',
        'coverage==7.3.2',
        'jupytext==1.16.4',
        'pytest>=7.1.2',
        'pre-commit>=2.20.0',
        'parameterized>=0.8.1',
        'Sphinx==5.0.0',
        'sphinx-toolbox==3.4.0',
        'sphinx-reload==0.2.0',
        'sphinx-notfound-page==0.8',
        'm2r2==0.3.2',
        'nbval==0.10.0',
        'sphinx-sitemap==2.2.0',
        'sphinx-rtd-theme==1.0.0',
        'sphinxcontrib-mermaid==0.8.1',
        'sphinx-copybutton==0.5.2',
        'myst_nb==0.17.2',
        'ruff',
        'pytest-rerunfailures',
    ],
    'ai': [
        'accelerate==0.20.1',
        'chardet==5.1.0',
        'datasets==2.14.6',
        'evaluate==0.4.1',
        'spacy>=2.3.5,<3.8.0',
        'torch>=1.8.1',
        'torchvision>=0.9.1',
        'transformers==4.30.2',
        'tensorflow-cpu==2.12.0',
        'timm==0.6.7',
        'mlflow==2.15.0',
    ],
}
