"""Store variables used for testing."""
import os.path

OFFLINE_PROJECT = os.path.join(os.path.dirname(os.path.realpath(__file__)), 'example_project_data')
TEST_DOCUMENT_ID = 44823
TEST_FALLBACK_DOCUMENT_ID = 5589024
TEST_CATEGORIZATION_DOCUMENT_ID = 141441
TEST_PROJECT_ID = 46
TEST_FALLBACK_PROJECT_ID = 14392
TEST_PAYSLIPS_CATEGORY_ID = 63
TEST_RECEIPTS_CATEGORY_ID = 735
TEST_SNAPSHOT_ID = 'ZGF0YV80Ni02NS56aXA='
TEST_SNAPSHOT_ID_2 = 'ZGF0YV8xNDM5Mi02Ni56aXA'
